# Generated by Django 4.2.7 on 2023-12-14 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
